In [1]:
import pandas as pd
import numpy as np

! `DataFrame`ni qatorlari yoki ustunlari bo'yicha tartilash mumkin

In [2]:
# KEling keyingi mashqlar uchun Githubdan kattaroq DF yuklab olamiz
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv', index_col=0)
df.head()

   price      brand    model  ...       state country      condition
0   6300     toyota  cruiser  ...  new jersey     usa   10 days left
1   2899       ford       se  ...   tennessee     usa    6 days left
2   5350      dodge      mpv  ...     georgia     usa    2 days left
3  25000       ford     door  ...    virginia     usa  22 hours left
4  27700  chevrolet     1500  ...     florida     usa  22 hours left

[5 rows x 12 columns]

In [3]:
df.sort_index(axis=1, inplace=True) # o'zgarishlar joyida saqlash
df

          brand   color  ...                  vin  year
0        toyota   black  ...    jtezu11f88k007763  2008
1          ford  silver  ...    2fmdk3gc4bbb02217  2011
2         dodge  silver  ...    3c4pdcgg5jt346413  2018
3          ford    blue  ...    1ftfw1et4efc23745  2014
4     chevrolet     red  ...    3gcpcrec2jg473991  2018
...         ...     ...  ...                  ...   ...
2494     nissan     red  ...    3n1cn7ap9kl880319  2019
2495     nissan  silver  ...    3n1cn7ap5jl884088  2018
2496     nissan  silver  ...    3n1cn7ap9jl884191  2018
2497     nissan   black  ...    3n1cn7ap3jl883263  2018
2498     nissan  silver  ...    3n1cn7ap4jl884311  2018

[2499 rows x 12 columns]

In [4]:
df['rating'] = df['year'].rank() # qaysi yildagi kam bo'lsa reytingi baland

In [5]:
df

          brand   color      condition  ...                  vin  year  rating
0        toyota   black   10 days left  ...    jtezu11f88k007763  2008    70.5
1          ford  silver    6 days left  ...    2fmdk3gc4bbb02217  2011   115.0
2         dodge  silver    2 days left  ...    3c4pdcgg5jt346413  2018  1362.0
3          ford    blue  22 hours left  ...    1ftfw1et4efc23745  2014   336.5
4     chevrolet     red  22 hours left  ...    3gcpcrec2jg473991  2018  1362.0
...         ...     ...            ...  ...                  ...   ...     ...
2494     nissan     red    1 days left  ...    3n1cn7ap9kl880319  2019  2005.5
2495     nissan  silver  21 hours left  ...    3n1cn7ap5jl884088  2018  1362.0
2496     nissan  silver  21 hours left  ...    3n1cn7ap9jl884191  2018  1362.0
2497     nissan   black    2 days left  ...    3n1cn7ap3jl883263  2018  1362.0
2498     nissan  silver  21 hours left  ...    3n1cn7ap4jl884311  2018  1362.0

[2499 rows x 13 columns]

In [6]:
df.sort_values('year')

          brand       color      condition  ...                  vin  year  rating
32    chevrolet         red  22 hours left  ...        1q87t3n166389  1973     1.0
405        ford       white  17 hours left  ...    2ftcf15y9eca14589  1984     2.0
545         gmc  light blue  18 hours left  ...    1gkfk16k5pj701631  1993     3.0
362        ford       white    2 days left  ...    1ftdf15y2rnb12612  1994     4.5
322        ford       green  19 hours left  ...    1fdee14n7rha47894  1994     4.5
...         ...         ...            ...  ...                  ...   ...     ...
426       lexus      silver    2 days left  ...    jtjam7bx4l5251250  2020  2475.5
806   chevrolet      silver    2 days left  ...    1gcgtcen7l1101496  2020  2475.5
2322     nissan        blue    2 days left  ...    1n4bl4cv4lc134145  2020  2475.5
2344     nissan        blue  14 hours left  ...    jn8at2mvxlw103235  2020  2475.5
1388       ford        gray    2 days left  ...    3fa6p0d98lr194138  2020  2475.5

[2499 rows x 13 columns]

In [8]:
df['rating'] = df['price'].rank(method='min') # qancha arzon bo'lsa reyting baland

In [9]:
df

          brand   color      condition  ...                  vin  year  rating
0        toyota   black   10 days left  ...    jtezu11f88k007763  2008   380.0
1          ford  silver    6 days left  ...    2fmdk3gc4bbb02217  2011   156.0
2         dodge  silver    2 days left  ...    3c4pdcgg5jt346413  2018   326.0
3          ford    blue  22 hours left  ...    1ftfw1et4efc23745  2014  1824.0
4     chevrolet     red  22 hours left  ...    3gcpcrec2jg473991  2018  2004.0
...         ...     ...            ...  ...                  ...   ...     ...
2494     nissan     red    1 days left  ...    3n1cn7ap9kl880319  2019   475.0
2495     nissan  silver  21 hours left  ...    3n1cn7ap5jl884088  2018   567.0
2496     nissan  silver  21 hours left  ...    3n1cn7ap9jl884191  2018   567.0
2497     nissan   black    2 days left  ...    3n1cn7ap3jl883263  2018   567.0
2498     nissan  silver  21 hours left  ...    3n1cn7ap4jl884311  2018   567.0

[2499 rows x 13 columns]

In [11]:
df.sort_values('price')

              brand     color      condition  ...                  vin  year  rating
410       chevrolet     green    2 days left  ...    2gcec19h8s1195266  1995     1.0
330            ford     green  19 hours left  ...    1falp62w5th144314  1996     1.0
331            ford       red  17 hours left  ...    1fmzk04136ga07119  2006     1.0
339            ford     black    2 days left  ...    3fafp37372r151014  2002     1.0
496            ford       red  17 hours left  ...    1ftef15n0tlc14455  1996     1.0
...             ...       ...            ...  ...                  ...   ...     ...
1215           ford     black  21 hours left  ...    1ft7w2bt0kec44818  2019  2495.0
277           dodge      blue  21 hours left  ...    2c3cdzl97kh518237  2019  2496.0
1336           ford  no_color    2 days left  ...    1ft8w3dt3kee48276  2019  2497.0
1340           ford  no_color    2 days left  ...    1ft8w4dt6ked32656  2019  2498.0
502   mercedes-benz    silver    2 days left  ...    wddjk7ea3hf044968  2017  2499.0

[2499 rows x 13 columns]

In [12]:
df['rating'] = df['mileage'].rank(method='average') # masofasi, o'rt qiymati

In [14]:
df.sort_values('mileage')

          brand       color      condition  ...                  vin  year  rating
545         gmc  light blue  18 hours left  ...    1gkfk16k5pj701631  1993     3.5
504   peterbilt        blue  17 hours left  ...    1xp4d49x1cd144875  2012     3.5
1619       ford       black    2 days left  ...    1fadp3k21hl268441  2017     3.5
309   chevrolet      maroon  18 hours left  ...    3gnek12t74g240524  2004     3.5
1236       ford    no_color    2 days left  ...    1fadp3j23dl155179  2013     3.5
...         ...         ...            ...  ...                  ...   ...     ...
531   chevrolet         red  21 hours left  ...    1gcgc24u53z128586  2003  2495.0
490   peterbilt        gold  17 hours left  ...    1xp4d49x9cd123630  2012  2496.0
516   peterbilt        blue  17 hours left  ...    1xp7d49x09d784257  2009  2497.0
1827       ford      silver  21 hours left  ...    1fadp3k21dl266148  2013  2498.0
528   peterbilt      color:  17 hours left  ...    1xp7d49x0ad793710  2010  2499.0

[2499 rows x 13 columns]