In [1]:
import pandas as pd
import numpy as np

In [23]:
# Keyingi mashqlar uchun ma'lumotlarni Githubdan yuklab olamiz
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv')
df

            model  year  price transmission  ...  fuelType  tax   mpg  engineSize
0             SLK  2005   5200    Automatic  ...    Petrol  325  32.1         1.8
1         S Class  2017  34948    Automatic  ...    Hybrid   20  61.4         2.1
2        SL CLASS  2016  49948    Automatic  ...    Petrol  555  28.0         5.5
3         G Class  2016  61948    Automatic  ...    Petrol  325  30.4         4.0
4         G Class  2016  73948    Automatic  ...    Petrol  325  30.1         4.0
...           ...   ...    ...          ...  ...       ...  ...   ...         ...
13114     C Class  2020  35999    Automatic  ...    Diesel  145  55.4         2.0
13115     B Class  2020  24699    Automatic  ...    Diesel  145  55.4         2.0
13116   GLC Class  2019  30999    Automatic  ...    Diesel  145  41.5         2.1
13117   CLS Class  2019  37990    Automatic  ...    Diesel  145  45.6         2.0
13118     S Class  2019  54999    Automatic  ...    Diesel  145  52.3         2.9

[13119 rows x 9 columns]

In [24]:
models = df['model'].unique()
models.sort()
models

array([' A Class', ' B Class', ' C Class', ' CL Class', ' CLA Class',
       ' CLC Class', ' CLK', ' CLS Class', ' E Class', ' G Class',
       ' GL Class', ' GLA Class', ' GLB Class', ' GLC Class',
       ' GLE Class', ' GLS Class', ' M Class', ' R Class', ' S Class',
       ' SL CLASS', ' SLK', ' V Class', ' X-CLASS', '180', '200', '220',
       '230'], dtype=object)

In [25]:
df['year'].unique()

array([2005, 2017, 2016, 2011, 2018, 2012, 2019, 2020, 2014, 2015, 2006,
       2010, 2004, 2008, 2013, 2007, 2009, 2003, 2001, 2002, 1998, 2000,
       1997, 1999, 1970])

In [26]:
df['fuelType'].unique()

array(['Petrol', 'Hybrid', 'Diesel', 'Other'], dtype=object)

Sonini bilmoqchi bo'lsak:

In [27]:
df['model'].value_counts()

 C Class      3747
 A Class      2561
 E Class      1953
 GLC Class     960
 GLA Class     847
 B Class       591
 CL Class      511
 GLE Class     461
 SL CLASS      260
 CLS Class     237
 V Class       207
 S Class       197
 GL Class      121
 SLK            95
 CLA Class      86
 X-CLASS        82
 M Class        79
 GLS Class      74
 GLB Class      19
 G Class        15
 CLK             7
 CLC Class       3
 R Class         2
230              1
220              1
200              1
180              1
Name: model, dtype: int64

In [28]:
df['fuelType'].value_counts()

Diesel    9187
Petrol    3752
Hybrid     173
Other        7
Name: fuelType, dtype: int64

In [29]:
df['transmission'].value_counts()

Semi-Auto    6848
Automatic    4825
Manual       1444
Other           2
Name: transmission, dtype: int64

In [30]:
df['model'].unique()

array([' SLK', ' S Class', ' SL CLASS', ' G Class', ' GLE Class',
       ' GLA Class', ' A Class', ' B Class', ' GLC Class', ' C Class',
       ' E Class', ' GL Class', ' CLS Class', ' CLC Class', ' CLA Class',
       ' V Class', ' M Class', ' CL Class', ' GLS Class', ' GLB Class',
       ' X-CLASS', '180', ' CLK', ' R Class', '230', '220', '200'],
      dtype=object)

In [31]:
models = [' SLK', ' B Class'] # bizga kerakli modellar
filtr = df['model'].isin(models) # modelga ko'ra df ga filtr yasadik
filtr

0         True
1        False
2        False
3        False
4        False
         ...
13114    False
13115     True
13116    False
13117    False
13118    False
Name: model, Length: 13119, dtype: bool

In [32]:
df2 = df[filtr] # filtrlangan df
df2

          model  year  price transmission  ...  fuelType  tax   mpg  engineSize
0           SLK  2005   5200    Automatic  ...    Petrol  325  32.1         1.8
12      B Class  2019  23750    Automatic  ...    Diesel  145  55.4         2.0
15      B Class  2017  15890    Automatic  ...    Diesel  150  68.9         1.5
18      B Class  2017  17513    Automatic  ...    Diesel  150  68.9         2.1
40          SLK  2014  15990    Automatic  ...    Petrol  205  43.5         1.8
...         ...   ...    ...          ...  ...       ...  ...   ...         ...
13033   B Class  2016  14599    Automatic  ...    Diesel   20  68.9         2.1
13073   B Class  2019  19350    Automatic  ...    Petrol  145  45.6         1.3
13108       SLK  2016  17499    Automatic  ...    Diesel   30  70.6         2.1
13111   B Class  2019  19344    Automatic  ...    Petrol  145  45.6         1.3
13115   B Class  2020  24699    Automatic  ...    Diesel  145  55.4         2.0

[686 rows x 9 columns]

In [33]:
filter = df['fuelType'].isin(['Diesel','Petrol'])

In [34]:
df[filter]

            model  year   price transmission  ...  fuelType  tax   mpg  engineSize
0             SLK  2005    5200    Automatic  ...    Petrol  325  32.1         1.8
2        SL CLASS  2016   49948    Automatic  ...    Petrol  555  28.0         5.5
3         G Class  2016   61948    Automatic  ...    Petrol  325  30.4         4.0
4         G Class  2016   73948    Automatic  ...    Petrol  325  30.1         4.0
5        SL CLASS  2011  149948    Automatic  ...    Petrol  570  21.4         6.2
...           ...   ...     ...          ...  ...       ...  ...   ...         ...
13114     C Class  2020   35999    Automatic  ...    Diesel  145  55.4         2.0
13115     B Class  2020   24699    Automatic  ...    Diesel  145  55.4         2.0
13116   GLC Class  2019   30999    Automatic  ...    Diesel  145  41.5         2.1
13117   CLS Class  2019   37990    Automatic  ...    Diesel  145  45.6         2.0
13118     S Class  2019   54999    Automatic  ...    Diesel  145  52.3         2.9

[12939 rows x 9 columns]

Filtrni to'g'ridan-to'g'ri yozish:

In [38]:
df3 = df[(df.year>=2018) & (df.price<20000)] 
df3
# yili 2018 dan baland, narxi 20000 dan kam mashinalar

          model  year  price transmission  ...  fuelType  tax   mpg  engineSize
86      A Class  2018  18220    Automatic  ...    Diesel  145  68.9         1.5
89      A Class  2019  18118    Automatic  ...    Diesel  145  68.9         1.5
90      A Class  2019  17990    Automatic  ...    Diesel  145  65.7         1.5
92      A Class  2018  18888    Automatic  ...    Diesel  145  67.3         1.5
93      A Class  2019  19840    Automatic  ...    Petrol  145  28.5         1.3
...         ...   ...    ...          ...  ...       ...  ...   ...         ...
13000   A Class  2018  16500    Semi-Auto  ...    Petrol  150  49.6         1.6
13013   B Class  2018  17995    Automatic  ...    Diesel  145  68.9         2.1
13018   A Class  2018  17600    Automatic  ...    Petrol  145  52.3         1.6
13073   B Class  2019  19350    Automatic  ...    Petrol  145  45.6         1.3
13111   B Class  2019  19344    Automatic  ...    Petrol  145  45.6         1.3

[749 rows x 9 columns]

Satrli qiymatni filtrlash

In [40]:
df[df.fuelType=='Hybrid']

          model  year  price transmission  ...  fuelType  tax    mpg  engineSize
1       S Class  2017  34948    Automatic  ...    Hybrid   20   61.4         2.1
77      S Class  2016  24880    Automatic  ...    Hybrid  190   42.4         3.5
137     C Class  2017  21000    Automatic  ...    Hybrid  140  134.5         2.0
327     E Class  2019  39998    Semi-Auto  ...    Hybrid  135  134.5         2.0
329     C Class  2016  18498    Semi-Auto  ...    Hybrid    0  134.5         2.0
...         ...   ...    ...          ...  ...       ...  ...    ...         ...
12687   C Class  2017  17480    Automatic  ...    Hybrid    0  134.5         2.0
12707   S Class  2019  56890    Automatic  ...    Hybrid  135  100.9         3.0
12713   C Class  2017  20480    Automatic  ...    Hybrid    0  134.5         2.0
12867   S Class  2017  36890    Automatic  ...    Hybrid   20   61.4         2.1
12999   C Class  2016  15999    Automatic  ...    Hybrid    0  134.5         2.0

[173 rows x 9 columns]