![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **1-QISM**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv", index_col=0)

### 1-VAZIFA. Yuqoridagi DF ustunlari nomini quyidagi qiymatlarga o'zgartiring va DF yuqorisidan 3 ta davlatni chiqaring
`['davlat','zichlik_km','zichlik_mi','aholi','maydoni']`

In [3]:
# JAVOBNI SHUYERGA YOZING
df.columns=['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

In [4]:
#@title To'g'ri javob
df.columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

## Yuqoridagi jadval dunyo davlatlarining aholi zichligi bo'yicha reytingini ko'rsatadi. 
DF indeksi sifatida davlatning zichlik reytingi olingan (aholi eng zich yashaydigan davlatlar yuqorida).

**Ustunlar:**

`davlat` - Davlat nomi

`zichlik_km` - har 1 kv.km. ga to'g'ri keluvchi aholi soni

`zichlik_mi` - har 1 kv.milyaga to'g'ri keluvchi aholi soni (milya - AQSh masofa o'lchov birligi)

`aholi` - 2021-yilga ko'rsa aholi soni (ming)

`maydoni` - davlat maydoni (kv.km)

### 2-VAZIFA. DF oxiridan 10 ta qator chiqaring.

In [5]:
# JAVOBNI SHUYERGA YOZING
df.tail(10)

                davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
223             Guyana      3.6765      9.5220    790.326   214969
224      French Guiana      3.6685      9.5015    306.448    83534
225           Suriname      3.6125      9.3564    591.800   163820
226          Australia      3.3526      8.6832  25788.215  7692024
227            Iceland      3.3335      8.6338    343.353   103000
228            Namibia      3.1338      8.1166   2587.344   825615
229     Western Sahara      2.3003      5.9577    611.875   266000
230           Mongolia      2.1286      5.5129   3329.289  1564110
231   Falkland Islands      0.2902      0.7517      3.533    12173
232          Greenland      0.0263      0.0680     56.877  2166086

### 3-VAZIFA. DF dan 10, 20, 100, 200-indekslarda turgan davlatlarni alohida DF ko'rinishida chiqaring.

In [6]:
# JAVOBNI SHUYERGA YOZING
df.loc[[10]]

       davlat  zichlik_km  zichlik_mi  aholi  maydoni
rank
10    Bermuda   1149.8148   2978.0204  62.09       54

### 4-VAZIFA. Davlatlar orasida `Uzbekistan`, `Hong-Kong`, `Antartica` borligini tekshiring

In [7]:
# JAVOBNI SHUYERGA YOZING
filtr = pd.Index(['Uzbekistan', 'Hong-Kong', 'Antarctica'])
filtr.isin(df['davlat'])

array([ True, False, False])

### 5-VAZIFA.
#### 5.1 DFning `davlat` nomli ustunini uning indeksi qilib belgilang. 
#### 5.2 `davlat` ustunini tashlab yuboring.
#### 5.3 DFni davlat nomi bo'yicha tartiblang

In [8]:
# JAVOBNI SHUYERGA YOZING
df.set_index('davlat', inplace=True)
df = df.sort_index()

In [9]:
df

                   zichlik_km  zichlik_mi      aholi  maydoni
davlat
Afghanistan           61.0757    158.1862  39835.428   652230
Albania               99.9351    258.8318   2872.933    28748
Algeria               18.7328     48.5179  44616.624  2381741
American Samoa       276.8844    717.1307     55.100      199
Andorra              165.2885    428.0971     77.355      468
...                       ...         ...        ...      ...
Wallis and Futuna     78.1268    202.3483     11.094      142
Western Sahara         2.3003      5.9577    611.875   266000
Yemen                 57.7509    149.5749  30490.640   527968
Zambia                25.1400     65.1125  18920.651   752612
Zimbabwe              38.6229    100.0333  15092.171   390757

[232 rows x 4 columns]

In [10]:
#@title Kutilayotgan natija

### 6-VAZIFA. DF dan `Uzbekistan`, `Malaysia`, `South Korea`, `France` davlatlari `aholi` va `maydoni` ustunlari bilan alohida DF ko'rinishida ajratib oling.

In [11]:
# JAVOBNI SHUYERGA YOZING
dfUMSKF = df.loc[['Uzbekistan', 'Malaysia', 'South Korea', 'France']][['aholi', 'maydoni']]
dfUMSKF

                 aholi  maydoni
davlat
Uzbekistan   33935.763   447400
Malaysia     32776.194   330803
South Korea  51305.186   100210
France       65426.179   551695

In [12]:
#@title O'xshash natija (boshqa davlatlar uchun)

### 7-VAZIFA. Asl DFning `aholi` ustuni qiymatlarini 1000 ga ko'paytiring.

In [13]:
# JAVOBNI SHUYERGA YOZING
df = df.sort_index()
def multiply_by_1000(val):
    return val * 1000
df.aholi = df['aholi'].apply(multiply_by_1000)
df

                   zichlik_km  zichlik_mi       aholi  maydoni
davlat
Afghanistan           61.0757    158.1862  39835428.0   652230
Albania               99.9351    258.8318   2872933.0    28748
Algeria               18.7328     48.5179  44616624.0  2381741
American Samoa       276.8844    717.1307     55100.0      199
Andorra              165.2885    428.0971     77355.0      468
...                       ...         ...         ...      ...
Wallis and Futuna     78.1268    202.3483     11094.0      142
Western Sahara         2.3003      5.9577    611875.0   266000
Yemen                 57.7509    149.5749  30490640.0   527968
Zambia                25.1400     65.1125  18920651.0   752612
Zimbabwe              38.6229    100.0333  15092171.0   390757

[232 rows x 4 columns]

In [14]:
#@title Kutilgan natija

DF ni `aholi` ustuni bo'yicha kamayish tartibida tahlang va aholisi eng kam 10 ta davlatni chiqaring.

In [15]:
# JAVOBNI SHUYERGA YOZING
df1 = df.sort_values(by='aholi', ascending=False)
df1.tail(10)

                           zichlik_km  zichlik_mi    aholi  maydoni
davlat
Tuvalu                       458.8846   1188.5112  11931.0       26
Wallis and Futuna             78.1268    202.3483  11094.0      142
Nauru                        517.9048   1341.3733  10876.0       21
Saint Barthelemy             471.7619   1221.8633   9907.0       21
Saint Pierre and Miquelon     23.8264     61.7105   5766.0      242
Montserrat                    48.7941    126.3768   4977.0      102
Falkland Islands               0.2902      0.7517   3533.0    12173
Niue                           6.2269     16.1277   1619.0      260
Tokelau                      114.4167    296.3392   1373.0       12
Vatican City                 800.0000   2072.0000    800.0        1

### 8-VAZIFA. DFni `maydoni` bo'yicha reytinglang (rank) va reytinglarni yangi `rank` ustuniga yozing.

In [16]:
# JAVOBNI SHUYERGA YOZING
df['rating'] = df['maydoni'].rank()
df

                   zichlik_km  zichlik_mi       aholi  maydoni  rating
davlat
Afghanistan           61.0757    158.1862  39835428.0   652230   192.0
Albania               99.9351    258.8318   2872933.0    28748    89.0
Algeria               18.7328     48.5179  44616624.0  2381741   223.0
American Samoa       276.8844    717.1307     55100.0      199    20.0
Andorra              165.2885    428.0971     77355.0      468    38.0
...                       ...         ...         ...      ...     ...
Wallis and Futuna     78.1268    202.3483     11094.0      142    15.0
Western Sahara         2.3003      5.9577    611875.0   266000   155.0
Yemen                 57.7509    149.5749  30490640.0   527968   183.0
Zambia                25.1400     65.1125  18920651.0   752612   194.0
Zimbabwe              38.6229    100.0333  15092171.0   390757   172.0

[232 rows x 5 columns]

In [17]:
#@title Kutilgan natija

#### `Uzbekistan`, `United Kingdom`, `Indonesia` davlatlari alohida df ko'rinishida chiqaring

In [18]:
# JAVOBNI SHUYERGA YOZING
dfUUKI = df.loc[['Uzbekistan','United Kingdom','Indonesia']]
dfUUKI

                zichlik_km  zichlik_mi        aholi  maydoni  rating
davlat
Uzbekistan         75.8511    196.4542   33935763.0   447400   176.0
United Kingdom    280.8033    727.2805   68207116.0   242900   153.0
Indonesia         145.1046    375.8210  276361783.0  1904569   218.0

In [19]:
#@title O'xshash natija (boshqa davlatlar uchun)

### 9-VAZIFA. DFni `davlat` nomi bo'yicha tartiblang.

In [20]:
# JAVOBNI SHUYERGA YOZING
dfname = df.sort_index()
dfname.head()

                zichlik_km  zichlik_mi       aholi  maydoni  rating
davlat
Afghanistan        61.0757    158.1862  39835428.0   652230   192.0
Albania            99.9351    258.8318   2872933.0    28748    89.0
Algeria            18.7328     48.5179  44616624.0  2381741   223.0
American Samoa    276.8844    717.1307     55100.0      199    20.0
Andorra           165.2885    428.0971     77355.0      468    38.0

In [21]:
#@title Kutilgan natija

#### DFdan 10,50,100,200-o'rinda turgan davlatlarni alohida DF ko'rinishida chiqaring

In [22]:
# JAVOBNI SHUYERGA YOZING
dfsel = df.iloc[[10,50,100,200]]
dfsel

                zichlik_km  zichlik_mi       aholi  maydoni  rating
davlat
Aruba             595.5778   1542.5464    107204.0      180    18.0
Czech Republic    135.9862    352.2044  10724555.0    78865   115.0
Jamaica           270.5362    700.6887   2973463.0    10991    68.0
Syria              98.6916    255.6111  18275702.0   185180   144.0

In [23]:
#@title O'xshash natija (boshqa qatorlar uchun)

### 10-VAZIFA. Quyidagi davlatlarning `aholi` sonini oddiy son ko'rinishida chiqaring:
- `Malaysia`
- `Nigeria`
- `Nepal`
- `Italy`

In [24]:
# JAVOBNI SHUYERGA YOZING
df.aholi['Malaysia']

32776194.000000004

In [25]:
#@title o'xshash natija (`Uzbekistan` uchun)
df.aholi['Uzbekistan']

33935763.0

**PANDAS. Yakuniy test. 1-QISM**

1. Aholi zichligi bo'yicha 3-o'rindagi davlat nomi

In [43]:
df_z = df.sort_values(by='zichlik_km', ascending=False)
df_z.iloc[[2]] # df_z.head()

           zichlik_km  zichlik_mi      aholi  maydoni  rating
davlat
Singapore   8305.1915  21510.4461  5896686.0      710    43.0

2. Zichligi bo'yicha oxiridan 3 o'rindagi davlat maydoni nechiga teng?

In [44]:
df_z = df.sort_values(by='zichlik_km', ascending=False)
df_z.iloc[[-3]] # df_z.tail()

          zichlik_km  zichlik_mi      aholi  maydoni  rating
davlat
Mongolia      2.1286      5.5129  3329289.0  1564110   214.0

3. Quyidagi davlatlarni zichligi bo'yicha o'sish tartibida tahlang:
Bermuda, Aruba, Slovakia, New Zealand

In [28]:
df_zich = df.loc[['Bermuda', 'Aruba', 'Slovakia', 'New Zealand']].sort_values(by='zichlik_km')
df_zich

             zichlik_km  zichlik_mi      aholi  maydoni  rating
davlat
New Zealand     17.9713     46.5457  4860643.0   270467   157.0
Slovakia       111.3592    288.4203  5460721.0    49037   103.0
Aruba          595.5778   1542.5464   107204.0      180    18.0
Bermuda       1149.8148   2978.0204    62090.0       54    11.0

4. Quyidagilardan qay biri DF tarkibida yo'q: Hong-Kong, Antarctica, Uzbekistan

In [29]:
filtr = pd.Index(['Uzbekistan', 'Hong-Kong', 'Antarctica'])
filtr.isin(df.index)

array([ True, False, False])

5. Davlat nomi bo'yicha tartiblangan DFning oxiridan 5-davlatning nomi nima?

In [36]:
df.iloc[-5].name

'Wallis and Futuna'

6. Uzbekistan, Malaysia, South Korea, France davlatlarini maydoni bo'yicha o'sish tartibida tahlang.

In [38]:
dfUMSKF = df.loc[['Uzbekistan', 'Malaysia', 'South Korea', 'France']][['aholi', 'maydoni']]
dfUMSKF.sort_values(by='maydoni')

                  aholi  maydoni
davlat
South Korea  51305186.0   100210
Malaysia     32776194.0   330803
Uzbekistan   33935763.0   447400
France       65426179.0   551695

7. Quyidagi aholisi eng kam davlatlarning aholisi sonini tanlang

In [39]:
dfTNSF = df.loc[['Tuvalu', 'Nauru', 'Saint Pierre and Miquelon', 'Falkland Islands']][['aholi']]
dfTNSF

                             aholi
davlat
Tuvalu                     11931.0
Nauru                      10876.0
Saint Pierre and Miquelon   5766.0
Falkland Islands            3533.0

8. Quyidagi sonlarni (reytinglarni) to'g'ri davlatlar bilan bog'lang.

In [40]:
dfUUKI = df.loc[['Uzbekistan','United Kingdom', 'Indonesia']]
dfUUKI

                zichlik_km  zichlik_mi        aholi  maydoni  rating
davlat
Uzbekistan         75.8511    196.4542   33935763.0   447400   176.0
United Kingdom    280.8033    727.2805   68207116.0   242900   153.0
Indonesia         145.1046    375.8210  276361783.0  1904569   218.0

9. Quyidagi davlatlar orasida 10,50,100,200-o'rinlarda turgan davlatlarni tanlang

In [41]:
df.iloc[[10,50,100,200]]

                zichlik_km  zichlik_mi       aholi  maydoni  rating
davlat
Aruba             595.5778   1542.5464    107204.0      180    18.0
Czech Republic    135.9862    352.2044  10724555.0    78865   115.0
Jamaica           270.5362    700.6887   2973463.0    10991    68.0
Syria              98.6916    255.6111  18275702.0   185180   144.0

10. DFdan Malaysia aholi sonini oddiy son ko'rinishida chiqarish uchun to'g'ri kod qaysi?

In [49]:
df.at['Malaysia','aholi'] # df.loc['Malaysia','aholi'] # df.aholi.loc['Malaysia']

32776194.000000004